# -*- coding: utf-8 -*-
"""fpl_bot.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1eJAHkgwfxiZdY7jEC0x4lZxDRDW6_K7a
"""

# The complete, assembled script

import requests
import json
import os
import smtplib
from email.mime.text import MIMEText
import pandas as pd
from datetime import datetime, timedelta


def get(url):
    response = requests.get(url)
    return json.loads(response.content)


def check_update(df):
    today = datetime.now()
    tomorrow = (today + timedelta(days=1)).timestamp()
    today = today.timestamp()
    df = df.loc[df.deadline_time_epoch > today]
    deadline = df.iloc[0].deadline_time_epoch
    return deadline < tomorrow


def get_data():
    data = get('https://fantasy.premierleague.com/api/bootstrap-static/')
    players_df = pd.DataFrame(data['elements'])
    teams_df = pd.DataFrame(data['teams'])
    events_df = pd.DataFrame(data['events'])

    today = datetime.now().timestamp()
    upcoming = events_df.loc[events_df.deadline_time_epoch > today]
    gameweek = upcoming.iloc[0].id

    if not check_update(upcoming):
        print("Deadline Too Far Away")
        return None, None, None

    fixtures = get(f'https://fantasy.premierleague.com/api/fixtures/?event={gameweek}')
    fixtures_df = pd.DataFrame(fixtures)

    players_df.chance_of_playing_next_round = players_df.chance_of_playing_next_round.fillna(100.0)
    players_df.chance_of_playing_this_round = players_df.chance_of_playing_this_round.fillna(100.0)

    teams = dict(zip(teams_df.id, teams_df.name))
    players_df['team_name'] = players_df['team'].map(teams)
    fixtures_df['team_a_name'] = fixtures_df['team_a'].map(teams)
    fixtures_df['team_h_name'] = fixtures_df['team_h'].map(teams)

    home_strength = dict(zip(teams_df.id, teams_df.strength_overall_home))
    away_strength = dict(zip(teams_df.id, teams_df.strength_overall_away))
    fixtures_df['team_a_strength'] = fixtures_df['team_a'].map(away_strength)
    fixtures_df['team_h_strength'] = fixtures_df['team_h'].map(home_strength)

    fixtures_df = fixtures_df.drop(columns=['id'])
    a_players = pd.merge(players_df, fixtures_df, how="inner", left_on=["team"], right_on=["team_a"])
    h_players = pd.merge(players_df, fixtures_df, how="inner", left_on=["team"], right_on=["team_h"])
    a_players['diff'] = a_players['team_a_strength'] - a_players['team_h_strength']
    h_players['diff'] = h_players['team_h_strength'] - h_players['team_a_strength']
    players_df = pd.concat([a_players, h_players])  # .append() no longer exists in pandas 2.x+

    return players_df, fixtures_df, gameweek


def calc_out_weight(players):
    players = players.copy()
    players['weight'] = 100
    players['weight'] -= players['diff'] / 3
    players['weight'] -= players['form'].astype("float") * 10
    players['weight'] += (100 - players['chance_of_playing_this_round'].astype("float")) * 0.2
    players.loc[players['element_type'] == 1, 'weight'] -= 10
    players.loc[players['weight'] < 0, 'weight'] = 0
    return players.sample(1, weights=players.weight)


def calc_in_weights(players):
    players = players.copy()
    players['weight'] = 1
    players['weight'] += players['diff'] / 3
    players['weight'] += players['form'].astype("float") * 10
    players['weight'] -= (100 - players['chance_of_playing_this_round'].astype("float")) * 0.2
    players.loc[players['weight'] < 0, 'weight'] = 0
    return players.sample(1, weights=players.weight)


def calc_starting_weight(players):
    players = players.copy()
    players['weight'] = 1
    players['weight'] += players['diff'] / 2
    players['weight'] += players['form'].astype("float") * 5
    players['weight'] -= (100 - players['chance_of_playing_this_round'].astype("float")) * 0.2
    players.loc[players['weight'] < 0, 'weight'] = 0
    return players.sort_values('weight', ascending=False)


def send_email_notification(player_out, player_in, captain, vice_captain):
    """Fire-and-forget info email. No approval step, just a summary of what happened."""
    sender = os.environ.get('SMTP_EMAIL')
    app_password = os.environ.get('SMTP_APP_PASSWORD')
    recipient = os.environ.get('NOTIFY_EMAIL')

    if not all([sender, app_password, recipient]):
        print("Email env vars not set — skipping notification.")
        return

    body = (
        "Your FPL team was updated automatically.\n\n"
        f"Transferred OUT: {player_out}\n"
        f"Transferred IN:  {player_in}\n"
        f"Captain:         {captain}\n"
        f"Vice-captain:    {vice_captain}\n"
    )
    msg = MIMEText(body)
    msg['Subject'] = "FPL Bot: Transfer made this gameweek"
    msg['From'] = sender
    msg['To'] = recipient

    try:
        with smtplib.SMTP_SSL('smtp.gmail.com', 465) as server:
            server.login(sender, app_password)
            server.sendmail(sender, recipient, msg.as_string())
        print("Notification email sent.")
    except Exception as e:
        # Don't let an email failure crash the whole run — the transfer already went through.
        print(f"Email failed to send: {e}")


def update_team(email, password, team_id, test_mode=True):
    players_df, fixtures_df, gameweek = get_data()
    if players_df is None:
        return  # deadline too far away, do nothing

    session = requests.session()
    login_data = {
        'login': email, 'password': password,
        'app': 'plfpl-web', 'redirect_uri': 'https://fantasy.premierleague.com/'
    }
    login_url = "https://users.premierleague.com/accounts/login/"
    session.post(url=login_url, data=login_data)

    url = f"https://fantasy.premierleague.com/api/my-team/{team_id}"
    team = json.loads(session.get(url).content)

    my_ids = [x['element'] for x in team['picks']]
    my_team = players_df.loc[players_df.id.isin(my_ids)]
    potential_players = players_df.loc[~players_df.id.isin(my_ids)]
    bank = team['transfers']['bank']

    # --- Pick player OUT ---
    player_out = calc_out_weight(my_team)
    my_team = my_team.loc[my_team.id != player_out.id.iat[0]]

    # --- Pick player IN ---
    position = player_out.element_type.iat[0]
    out_cost = player_out.now_cost.iat[0]
    budget = bank + out_cost
    dups_team = my_team.pivot_table(index=['team'], aggfunc='size')
    invalid_teams = dups_team.loc[dups_team == 3].index.tolist()

    potential_players = potential_players.loc[~potential_players.team.isin(invalid_teams)]
    potential_players = potential_players.loc[potential_players.element_type == position]
    potential_players = potential_players.loc[potential_players.now_cost <= budget]

    player_in = calc_in_weights(potential_players)
    my_team = pd.concat([my_team, player_in])

    print(f"OUT: {player_out.web_name.iat[0]}  IN: {player_in.web_name.iat[0]}")

    if not test_mode:
        headers = {
            'content-type': 'application/json',
            'origin': 'https://fantasy.premierleague.com',
            'referer': 'https://fantasy.premierleague.com/transfers'
        }
        transfers = [{
            "element_in": int(player_in.id.iat[0]),
            "element_out": int(player_out.id.iat[0]),
            "purchase_price": int(player_in.now_cost.iat[0]),
            "selling_price": int(player_out.now_cost.iat[0])
        }]
        transfer_payload = {"transfers": transfers, "chip": None, "entry": team_id, "event": int(gameweek)}
        session.post(url='https://fantasy.premierleague.com/api/transfers/',
                     data=json.dumps(transfer_payload), headers=headers)

    # --- Pick starting XI + captain ---
    my_team = calc_starting_weight(my_team)
    goalies = my_team.loc[my_team.element_type == 1]
    defenders = my_team.loc[my_team.element_type == 2]
    outfield_players = my_team.loc[my_team.element_type > 2]

    captain_id = outfield_players.id.iat[0]
    vice_captain_id = outfield_players.id.iat[1]
    captain_name = outfield_players.web_name.iat[0]
    vice_captain_name = outfield_players.web_name.iat[1]

    starters = pd.concat([goalies.head(1), defenders.head(3), outfield_players.head(7)])
    subs = pd.concat([goalies.tail(1), defenders.tail(2), outfield_players.tail(1)])

    print(f"Captain: {captain_name}, Vice: {vice_captain_name}")

    if not test_mode:
        picks = []
        count = 1
        for i in range(1, 5):
            players = starters.loc[starters.element_type == i]
            for ide in players.id.tolist():
                is_cap = ide == captain_id
                is_vc = ide == vice_captain_id
                picks.append({"element": int(ide), "is_captain": is_cap,
                              "is_vice_captain": is_vc, "position": count})
                count += 1
        for ide in subs.id.tolist():
            picks.append({"element": int(ide), "is_captain": False,
                          "is_vice_captain": False, "position": count})
            count += 1

        team_sheet = {"picks": picks, "chip": None}
        headers = {
            'content-type': 'application/json',
            'origin': 'https://fantasy.premierleague.com',
            'referer': 'https://fantasy.premierleague.com/my-team'
        }
        session.post(url=f'https://fantasy.premierleague.com/api/my-team/{team_id}/',
                     json=team_sheet, headers=headers)
        print("Team updated live.")

        # Info-only email — no approval step, sent after the change is already made.
        send_email_notification(
            player_out.web_name.iat[0], player_in.web_name.iat[0],
            captain_name, vice_captain_name
        )
    else:
        print("TEST MODE — nothing was submitted to FPL, no email sent.")


# --- Lambda entry point ---
def lambda_handler(event, context):
    email = os.environ.get('FPL_EMAIL')
    password = os.environ.get('FPL_PASSWORD')
    team_id = os.environ.get('FPL_TEAM_ID')
    update_team(email, password, team_id, test_mode=False)