# -*- coding: utf-8 -*-
"""fpl_bot.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1eJAHkgwfxiZdY7jEC0x4lZxDRDW6_K7a
"""

import requests
import json
import os
import smtplib
from email.mime.text import MIMEText
import pandas as pd
from datetime import datetime, timedelta

# ---- Tunable constants ----
TRANSFER_HIT_COST = 4          # points lost per transfer beyond the free allowance
MIN_TRANSFER_GAIN = 0.5        # minimum projected-points improvement required to transfer at all
TOP_N_CANDIDATES = 3           # #3 shortlist size before any randomness
SSM_PARAM_NAME = "/fpl-bot/last-processed-gameweek"  # #9
UNAVAILABLE_STATUSES = {'i', 's', 'u', 'n'}          # #4 injured / suspended / unavailable / not in squad
STATUS_PENALTY = {'a': 0, 'd': -3, 'i': -50, 's': -50, 'u': -50, 'n': -50}


def get(url):
    response = requests.get(url)
    return json.loads(response.content)


def check_update(events_df):
    today = datetime.now()
    tomorrow = (today + timedelta(days=1)).timestamp()
    today_ts = today.timestamp()
    upcoming = events_df.loc[events_df.deadline_time_epoch > today_ts]
    if upcoming.empty:
        return False, None
    deadline = upcoming.iloc[0].deadline_time_epoch
    gameweek = upcoming.iloc[0].id
    return deadline < tomorrow, gameweek


# --- #9 Idempotency: remember which gameweek was last actioned ---
def already_processed(gameweek):
    import boto3
    ssm = boto3.client('ssm')
    try:
        resp = ssm.get_parameter(Name=SSM_PARAM_NAME)
        return int(resp['Parameter']['Value']) == gameweek
    except ssm.exceptions.ParameterNotFound:
        return False


def mark_processed(gameweek):
    import boto3
    ssm = boto3.client('ssm')
    ssm.put_parameter(Name=SSM_PARAM_NAME, Value=str(gameweek), Type='String', Overwrite=True)


def get_data(bootstrap_data, gameweek):
    players_df = pd.DataFrame(bootstrap_data['elements'])
    teams_df = pd.DataFrame(bootstrap_data['teams'])

    fixtures = get(f'https://fantasy.premierleague.com/api/fixtures/?event={gameweek}')
    fixtures_df = pd.DataFrame(fixtures)

    # #1 Forward-looking expected points instead of backward-looking 'form'
    players_df['ep_next'] = players_df['ep_next'].astype(float)

    teams = dict(zip(teams_df.id, teams_df.name))
    players_df['team_name'] = players_df['team'].map(teams)

    if fixtures_df.empty:
        players_df['diff'] = 0
        players_df['fixture_count'] = 0
    else:
        home_strength = dict(zip(teams_df.id, teams_df.strength_overall_home))
        away_strength = dict(zip(teams_df.id, teams_df.strength_overall_away))
        fixtures_df['team_a_strength'] = fixtures_df['team_a'].map(away_strength)
        fixtures_df['team_h_strength'] = fixtures_df['team_h'].map(home_strength)

        a_players = pd.merge(players_df, fixtures_df, how="inner", left_on=["team"], right_on=["team_a"])
        h_players = pd.merge(players_df, fixtures_df, how="inner", left_on=["team"], right_on=["team_h"])
        a_players['diff'] = a_players['team_a_strength'] - a_players['team_h_strength']
        h_players['diff'] = h_players['team_h_strength'] - h_players['team_a_strength']

        # #7 Double/blank gameweeks: collapse back to ONE row per player, counting fixtures
        fixture_rows = pd.concat([a_players, h_players])  # .append() no longer exists in pandas 2.x+
        per_player = fixture_rows.groupby('id').agg(
            diff=('diff', 'mean'),
            fixture_count=('diff', 'size')
        ).reset_index()

        players_df = players_df.merge(per_player, on='id', how='left')
        players_df['diff'] = players_df['diff'].fillna(0)
        players_df['fixture_count'] = players_df['fixture_count'].fillna(0)  # 0 = blank gameweek

    # Composite score: expected points scaled by fixture count (0 for a blank, ~2x for a double),
    # nudged by fixture difficulty, and #4 penalized by availability status.
    players_df['score'] = (
        (players_df['ep_next'] * players_df['fixture_count'])
        + (players_df['diff'] / 3)
        + players_df['status'].map(STATUS_PENALTY).fillna(-50)
    )

    return players_df, fixtures_df


# --- #3 Shortlist top/bottom candidates instead of a lottery across the whole pool ---
def pick_out_candidate(my_team):
    worst = my_team.sort_values('score').head(TOP_N_CANDIDATES)
    weights = worst['score'].max() - worst['score'] + 1  # worse players are more likely picked
    return worst.sample(1, weights=weights)


def pick_in_candidate(potential_players):
    best = potential_players.sort_values('score', ascending=False).head(TOP_N_CANDIDATES)
    if best.empty:
        return None
    weights = best['score'] - best['score'].min() + 1
    return best.sample(1, weights=weights)


# --- #5 Legal FPL formation: 1 GK, 3-5 DEF, 2-5 MID, 1-3 FWD, 11 starters total ---
def pick_starting_xi(squad_df):
    squad_df = squad_df.sort_values('score', ascending=False)
    gk = squad_df[squad_df.element_type == 1]
    df_ = squad_df[squad_df.element_type == 2]
    mid = squad_df[squad_df.element_type == 3]
    fwd = squad_df[squad_df.element_type == 4]

    starters = pd.concat([gk.head(1), df_.head(3), mid.head(2), fwd.head(1)])  # legal minimum: 1-3-2-1
    counts = {2: 3, 3: 2, 4: 1}
    caps = {2: 5, 3: 5, 4: 3}

    remaining_pool = pd.concat([df_.iloc[3:], mid.iloc[2:], fwd.iloc[1:]]).sort_values('score', ascending=False)
    extra_needed = 4  # 11 total - 7 already picked
    extras = []
    for _, player in remaining_pool.iterrows():
        if extra_needed == 0:
            break
        et = player['element_type']
        if counts[et] < caps[et]:
            extras.append(player)
            counts[et] += 1
            extra_needed -= 1

    if extras:
        starters = pd.concat([starters, pd.DataFrame(extras)])

    subs = squad_df.loc[~squad_df.id.isin(starters.id)]
    return starters, subs


def send_email_notification(status_line, player_out, player_in, captain, vice_captain):
    """Fire-and-forget info email. No approval step, just a summary of what happened."""
    sender = os.environ.get('SMTP_EMAIL')
    app_password = os.environ.get('SMTP_APP_PASSWORD')
    recipient = os.environ.get('NOTIFY_EMAIL')

    if not all([sender, app_password, recipient]):
        print("Email env vars not set — skipping notification.")
        return

    body = (
        "Your FPL team was updated automatically.\n\n"
        f"{status_line}\n\n"
        f"Transferred OUT: {player_out}\n"
        f"Transferred IN:  {player_in}\n"
        f"Captain:         {captain}\n"
        f"Vice-captain:    {vice_captain}\n"
    )
    msg = MIMEText(body)
    msg['Subject'] = "FPL Bot: Team updated this gameweek"
    msg['From'] = sender
    msg['To'] = recipient

    try:
        with smtplib.SMTP_SSL('smtp.gmail.com', 465) as server:
            server.login(sender, app_password)
            server.sendmail(sender, recipient, msg.as_string())
        print("Notification email sent.")
    except Exception as e:
        # Don't let an email failure crash the whole run — the transfer already went through.
        print(f"Email failed to send: {e}")


def update_team(email, password, team_id, test_mode=True):
    bootstrap_data = get('https://fantasy.premierleague.com/api/bootstrap-static/')
    events_df = pd.DataFrame(bootstrap_data['events'])

    should_update, gameweek = check_update(events_df)
    if not should_update:
        print("Deadline Too Far Away")
        return

    # #9 Skip if this gameweek was already actioned (only checked for real runs, not test_mode)
    if not test_mode and already_processed(gameweek):
        print(f"Gameweek {gameweek} already processed — skipping to avoid a duplicate transfer.")
        return

    players_df, fixtures_df = get_data(bootstrap_data, gameweek)

    session = requests.session()
    login_data = {
        'login': email, 'password': password,
        'app': 'plfpl-web', 'redirect_uri': 'https://fantasy.premierleague.com/'
    }
    login_url = "https://users.premierleague.com/accounts/login/"
    session.post(url=login_url, data=login_data)

    url = f"https://fantasy.premierleague.com/api/my-team/{team_id}"
    team_response = session.get(url)

    # #8 Confirm login actually worked before doing anything else
    try:
        team = team_response.json()
        if 'picks' not in team:
            raise ValueError("no picks in response")
    except Exception:
        raise Exception(
            "Could not fetch your team — login likely failed. "
            "Double-check FPL_EMAIL and FPL_PASSWORD."
        )

    my_ids = [x['element'] for x in team['picks']]
    my_team = players_df.loc[players_df.id.isin(my_ids)]
    potential_players = players_df.loc[~players_df.id.isin(my_ids)]
    bank = team['transfers']['bank']

    # #2 Only transfer if it's free, or the gain is big enough to justify a -4 hit
    free_transfers = team['transfers']['limit']
    made_already = team['transfers']['made']
    hit_cost = team['transfers'].get('cost') or TRANSFER_HIT_COST
    has_free_transfer = (
        free_transfers is None
        or made_already < free_transfers
        or team['transfers'].get('status') == 'unlimited'  # wildcard/free hit active
    )

    player_out = pick_out_candidate(my_team)
    position = player_out.element_type.iat[0]
    out_cost = player_out.now_cost.iat[0]
    budget = bank + out_cost

    dups_team = my_team.loc[my_team.id != player_out.id.iat[0]].pivot_table(index=['team'], aggfunc='size')
    invalid_teams = dups_team.loc[dups_team == 3].index.tolist()

    candidates = potential_players.loc[
        (~potential_players.team.isin(invalid_teams)) &
        (potential_players.element_type == position) &
        (potential_players.now_cost <= budget) &
        (~potential_players.status.isin(UNAVAILABLE_STATUSES))  # #4
    ]
    player_in = pick_in_candidate(candidates)

    made_transfer = False
    if player_in is not None:
        gain = player_in.score.iat[0] - player_out.score.iat[0]
        required_gain = MIN_TRANSFER_GAIN if has_free_transfer else (hit_cost + MIN_TRANSFER_GAIN)

        if gain >= required_gain:
            made_transfer = True
            my_team = my_team.loc[my_team.id != player_out.id.iat[0]]
            my_team = pd.concat([my_team, player_in])
            print(f"OUT: {player_out.web_name.iat[0]}  IN: {player_in.web_name.iat[0]} "
                  f"(projected gain: {gain:.2f}, free transfer: {has_free_transfer})")

            if not test_mode:
                headers = {
                    'content-type': 'application/json',
                    'origin': 'https://fantasy.premierleague.com',
                    'referer': 'https://fantasy.premierleague.com/transfers'
                }
                transfers = [{
                    "element_in": int(player_in.id.iat[0]),
                    "element_out": int(player_out.id.iat[0]),
                    "purchase_price": int(player_in.now_cost.iat[0]),
                    "selling_price": int(player_out.now_cost.iat[0])
                }]
                transfer_payload = {"transfers": transfers, "chip": None, "entry": team_id, "event": int(gameweek)}
                session.post(url='https://fantasy.premierleague.com/api/transfers/',
                             data=json.dumps(transfer_payload), headers=headers)
        else:
            print(f"Best available transfer only gains {gain:.2f} pts "
                  f"(needed {required_gain:.2f}) — skipping transfer this week.")
    else:
        print("No valid transfer candidates found — skipping transfer this week.")

    # --- Pick starting XI + captain (#5, #6) ---
    starters, subs = pick_starting_xi(my_team)
    starters_sorted = starters.sort_values('score', ascending=False)
    captain_id, captain_name = starters_sorted.iloc[0].id, starters_sorted.iloc[0].web_name
    vice_captain_id, vice_captain_name = starters_sorted.iloc[1].id, starters_sorted.iloc[1].web_name

    print(f"Captain: {captain_name}, Vice: {vice_captain_name}")

    if not test_mode:
        picks = []
        count = 1
        for i in range(1, 5):
            players = starters.loc[starters.element_type == i]
            for ide in players.id.tolist():
                picks.append({"element": int(ide), "is_captain": ide == captain_id,
                              "is_vice_captain": ide == vice_captain_id, "position": count})
                count += 1
        for ide in subs.id.tolist():
            picks.append({"element": int(ide), "is_captain": False,
                          "is_vice_captain": False, "position": count})
            count += 1

        team_sheet = {"picks": picks, "chip": None}
        headers = {
            'content-type': 'application/json',
            'origin': 'https://fantasy.premierleague.com',
            'referer': 'https://fantasy.premierleague.com/my-team'
        }
        session.post(url=f'https://fantasy.premierleague.com/api/my-team/{team_id}/',
                     json=team_sheet, headers=headers)
        print("Team updated live.")

        mark_processed(gameweek)  # #9

        status_line = "A transfer was made." if made_transfer else "No transfer met the value bar this week — lineup/captain only."
        send_email_notification(
            status_line,
            player_out.web_name.iat[0] if made_transfer else "—",
            player_in.web_name.iat[0] if made_transfer else "—",
            captain_name, vice_captain_name
        )
    else:
        print("TEST MODE — nothing was submitted to FPL, no email sent.")


# --- Lambda entry point ---
def lambda_handler(event, context):
    email = os.environ.get('FPL_EMAIL')
    password = os.environ.get('FPL_PASSWORD')
    team_id = os.environ.get('FPL_TEAM_ID')
    update_team(email, password, team_id, test_mode=False)